"""
Initial migration

Revision ID: d7b080ab3ec1
Revises: 
Create Date: 2023-06-07 14:53:12.251940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b080ab3ec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the column already exists
    conn = op.get_bind()
    result = conn.execute(
        "PRAGMA table_info(transactions) WHERE name='user_id'"
    )
    column_exists = bool(result.first())

    if not column_exists:
        op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=True))
        op.execute("UPDATE transactions SET user_id = NULL")
        op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    # ### end Alembic commands ###
